# fly.toml
app = "rito-labeler-kit"   # Fly.io 上でのアプリ名
primary_region = "lax" # 最初に作るリージョン（例: ロサンゼルス）

[build]
  # Dockerfile がある場合は自動で使われます
  image = "Dockerfile"

[env]
  LABELER_DID = "あなたのDID"
  LABELER_SIGNED_SEC_KEY = "秘密鍵"
  DB_PATH = "/data/"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080
    handlers = ["http"]
